// Required until NodeNext becomes stable

export enum Commands {
  USER_CONNECTED = 'USER_CONNECTED',
  USER_DISCONNECTED = 'DISCONN',
  NAME = 'NAME',
  NEW_USER_SET = 'NEW_USER_SET',
  GET_USERS_LIST = 'GET_USERS_LIST',
  ROOM_MESSAGE = 'ROOM_MESSAGE',

  CHALLENGE = 'CHALLENGE',
  CHALLENGE_CONFIRM = 'CHALLENGE_CONFIRM',
  CHALLENGE_CLOSE = 'CHALLENGE_CLOSED',

  PRIVATE_MESSAGE = 'PRIVATE_MESSAGE',

  START_CHOICES = 'START_CHOICES',
  SET_CHOICES = 'SET_CHOICES',
  CLOSE_GAME = 'CLOSE_GAME',
  ROUND_STARTED = 'ROUND_STARTED',
  SET_CHOOSEN_SPACESHIPS = 'SET_CHOOSEN_SPACESHIPS',
  SET_SPACESHIP_DESTINATION = 'SET_SPACESHIP_DESTINATION',
  SET_SPACESHIP_TARGET = 'SET_SPACESHIP_TARGET',
  SET_PLAYER_READY = 'SET_PLAYER_READY',

  USER_IS_PLAYING = 'USER_IS_PLAYING',
  USER_IS_BACK_FROM_GAME = 'USER_IS_BACK_FROM_GAME',

  COMMAND_PROCESSED = 'COMMAND_PROCESSED',
  COMMAND_ERROR = 'COMMAND_ERROR',
}

export type User = {
  name: string
  id: string
  isPlaying: boolean
}

export enum SpaceshipsTypes {
  SPACESHIP1 = 'SPACESHIP1',
  SPACESHIP2 = 'SPACESHIP2',
  SPACESHIP3 = 'SPACESHIP3',
}

export enum WeaponTypes {
  SINGLE_BULLET = 'SINGLE_BULLET',
}

export const ROUND_SECONDS_LIMIT = 30

export const ROUND_ANIMATION_SECONDS_LIMIT = 15

export const MAX_ROUNDS = 10

export const CHOICE_SECONDS_LIMIT = 15

export const CHALLENGE_SECONDS_LIMIT = 15

export const VERSION = '0.0.1'
