export enum Commands {
  USER_CONNECTED = 'USER_CONNECTED',
  USER_DISCONNECTED = 'DISCONN',
  NAME = 'NAME',
  NEW_USER_SET = 'NEW_USER_SET',
  GET_USERS_LIST = 'GET_USERS_LIST',
  ROOM_MESSAGE = 'ROOM_MESSAGE',

  CHALLENGE = 'CHALLENGE',
  CHALLENGE_CONFIRM = 'CHALLENGE_CONFIRM',
  CHALLENGE_CLOSE = 'CHALLENGE_CLOSED',

  PRIVATE_MESSAGE = 'PRIVATE_MESSAGE',

  CLOSE_GAME = 'CLOSE_GAME',
  ROUND_STARTED = 'ROUND_STARTED',
  SET_CHOOSEN_SPACESHIPS = 'SET_CHOOSEN_SPACESHIPS',
  SET_SPACESHIP_DESTINATION = 'SET_SPACESHIP_DESTINATION',
  SET_SPACESHIP_TARGET = 'SET_SPACESHIP_TARGET',
  SET_PLAYER_READY = 'SET_PLAYER_READY',

  COMMAND_PROCESSED = 'COMMAND_PROCESSED',
  COMMAND_ERROR = 'COMMAND_ERROR',
}


