name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:

  lint-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install
    - run: cd ./phaser_game && yarn install
    - run: cd ./phaser_game && yarn lint

  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./phaser_game
    needs: [lint-ui]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install
    - run: yarn build
   
  lint-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install
    - run: cd ./node_server && yarn install
    - run: cd ./node_server && yarn lint
    
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node_server
    needs: [lint-backend]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install
    - run: yarn test

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node_server
    needs: [test-backend]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: yarn install
    - run: yarn build
